### PR TITLE
seed database completed

### PR DESCRIPTION
**Pull request by gustavoperess**

### CODE REVIEW

**Review by JonnySB — APPROVED** [review]
Looks good to me. I might do a few naming changes when merged with mine / update the seeds to be what I need for testing - but all in all think it has everything we need! Good work!

**Review by MartyPru — APPROVED** [review]
Looks good! Help_offers is missing a bid field + status won't work as a Boolean cause there'll be more than 2 statuses (approved, pending, rejected). I'll make those changes to the file before submitting my PR though! Good work :)

**Comment by aisha-png** [comment]
Looks good to me too. Like Jonny said, when I merge with mine, I will update my queries in my repository to match the order you provided for inserting into and getting data from the table.

**Review by aisha-png — APPROVED** [review]

**Review by aisha-png — APPROVED** [review]
Looks good to me too. Like Jonny and Marty said, when I merge with mine, I will update my queries in my repository to match the order you provided for inserting into and getting data from the table. I'm also still wondering, when I merge, if i should add a plant filed to the table which is an array of the plant_ids

**Comment by mahlvm** [comment]
Plants look good for me and I agree with you about "watering frequency", maybe is easier it be an int. For now, I will merge it and keep how it is.

**Pull request merged**
